### ISSUE TITLE
Adversary access to victim's actions

### ISSUE THREAD

**Issue by apighetti** [T3AS/MAD-ARL#1]
Hi, I've recently found your work and found it very interesting, especially because of the non zero-sum nature of the project in the context of adversarial policy learning. Also, thank you for the open-source code, it's really useful for understanding the inner mechanisms of your algorithm. Reading through your paper, thanks to your clear explanation, I could clearly follow and understand the motivations and the implementation details of MAD-ARL. Driven by curiosity, here are some questions I have for you in this context.

While also studying your code, it remains unclear to me how the adversary agent is provided access to the action state sampled from the victim's policy during the adversarial training phase. Is it through its observations and if yes, how? If not, how is it embedded?

Also, is there any other major difference between the adversary training structure (obs, actions, algorithm loss, etc.) and the victim agents?

Sorry if I misunderstood something crucial about your pipeline and thank you in advance for your response!

**Comment by AizazSharif** [comment]
Hi @apighetti 

Sorry for such a delayed response. I was on parental leave plus stuck on other tasks.

Regarding your concern, the adversary driving agent only observes the driving actions of the victim without access to the victim's input or output actions. Thus, it learns to drive or take actions in such a way that the movements of adversarial agents observed by victim policies will feel natural since there is no extra adversarial attack or noise added by force. This phenomenon depicts the issue with RL-based agents against whom you can easily train an adversary and such adversarial actions will confuse the victim RL policies.

The only difference between adversarial and victim-agent learning is the reward function. We propose two adversarial reward functions to train and compare the efficiency of both types of adversarial agents.

**Comment by apighetti** [comment]
Hi @AizazSharif

Thank you for your exhaustive response and congratulations!

The only doubt I have left, and sorry if I'm being tedious but I would really love to further study this subject, is regarding the composition of the adversary observation space. As far as I understood from your response, the victim's action is not included in the observations itself but the adversary learns a policy by naturally observing the scene. Did I understand correctly? 

Thank you again for your response and time.

**Comment by AizazSharif** [comment]
Yes, your understanding is correct. The victim's action is not included in the observations but rather the adversary learns a policy by naturally observing the scene where the victim normally drives in front of it.

You're welcome! It was my pleasure to assist you. Let me know if there's anything else I can help you with.
